- name: payment conf
  hosts: payment
  become: yes
  tasks:
  - name: install python
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - gcc
      - python3-devel

  - name: creating user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop system user
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
     path: /app
     state: absent
    
  - name: Create a directory 
    ansible.builtin.file:
     path: /app
     state: directory

  - name: delete old content
    ansible.builtin.file:
      path: /tmp/payment
      state: absent  

  - name: Download catalogue zip file
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
     dest: /tmp/payment.zip
  
  - name: Unzip file
    ansible.builtin.unarchive:
     src: /tmp/payment.zip
     dest: /app
     remote_src: yes

  - name: install python dependencies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: Copy service files
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: system start and daemon-reload
    ansible.builtin.systemd_service:
      name: payment
      state: started
      enabled: yes
      daemon-reload: true
