- name: shipping conf
  hosts: shipping
  become: yes
  tasks:

  - name: install maven
    ansible.builtin.package:
      name: maven
      state: present

  - name: install python libraries
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{item}}"
    loop:
      - cryptography
      - pyMySQL


  - name: user add
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      home: /app
      shell: /sbin/nologin
  
  - name: cleaning app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete old content
    ansible.builtin.file:
      path: /tmp/user
      state: absent

  - name: download zip file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Unzip file
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes

  - name: Installing dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: moving jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: install mysql
    ansible.builtin.package:
     name: mysql
     state: present

  - name: Import schema.sql
    ansible.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.mahidevops.fun
      login_user: root
      login_password: RoboShop@1
      target: "{{item}}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql


  - name: start and enable 
    ansible.builtin.systemd_service:
      name: shipping
      state: started
      enabled: yes
      daemon-reload: True
